Team Name: Te-Data
Team members: Malak Hatem
Radwa Hussein
Ziad Ramzy
Mostafa Ahmed
Ahmed Hossam

In [29]:
import pandas as pd
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
import sqlite3
pd.options.display.width = 120

In [2]:
con = sqlite3.connect('E:/Semester Nine/DE/soccer/database.sqlite')
country = pd.read_sql_query("SELECT * from country", con)
League = pd.read_sql_query("SELECT * from League", con)
Match = pd.read_sql_query("SELECT * from Match", con)
Player = pd.read_sql_query("SELECT * from Player", con)
Player_Attributes = pd.read_sql_query("SELECT * from Player_Attributes", con)
Team = pd.read_sql_query("SELECT * from Team", con)
Team_Attributes = pd.read_sql_query("SELECT * from Team_Attributes", con)

In [3]:
country.head(11)

       id         name
0       1      Belgium
1    1729      England
2    4769       France
3    7809      Germany
4   10257        Italy
5   13274  Netherlands
6   15722       Poland
7   17642     Portugal
8   19694     Scotland
9   21518        Spain
10  24558  Switzerland

In [4]:
League.head(11)

       id  country_id                      name
0       1           1    Belgium Jupiler League
1    1729        1729    England Premier League
2    4769        4769            France Ligue 1
3    7809        7809     Germany 1. Bundesliga
4   10257       10257             Italy Serie A
5   13274       13274    Netherlands Eredivisie
6   15722       15722        Poland Ekstraklasa
7   17642       17642  Portugal Liga ZON Sagres
8   19694       19694   Scotland Premier League
9   21518       21518           Spain LIGA BBVA
10  24558       24558  Switzerland Super League

In [5]:
Match.head(10)

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
5,6,1,1,2008/2009,1,2008-09-24 00:00:00,492478,8203,8342,1,...,1.67,4.35,3.40,1.70,4.50,3.40,1.70,NaN,NaN,NaN
6,7,1,1,2008/2009,1,2008-08-16 00:00:00,492479,9999,8571,2,...,3.60,2.10,3.25,3.00,1.85,3.25,3.75,2.10,3.25,3.10
7,8,1,1,2008/2009,1,2008-08-16 00:00:00,492480,4049,9996,1,...,2.40,2.80,3.25,2.25,2.80,3.20,2.25,2.88,3.25,2.20
8,9,1,1,2008/2009,1,2008-08-16 00:00:00,492481,10001,9986,1,...,3.10,2.25,3.25,2.80,2.20,3.30,2.80,2.25,3.20,2.80
9,10,1,1,2008/2009,10,2008-11-01 00:00:00,492564,8342,8571,4,...,10.00,1.30,4.35,8.50,1.25,5.00,10.00,1.29,4.50,9.00

In [6]:
Team_Attributes.head(10)

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,1,434,9930,2010-02-22 00:00:00,60,Balanced,NaN,Little,50,Mixed,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
1,2,434,9930,2014-09-19 00:00:00,52,Balanced,48.0,Normal,56,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,3,434,9930,2015-09-10 00:00:00,47,Balanced,41.0,Normal,54,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,4,77,8485,2010-02-22 00:00:00,70,Fast,NaN,Little,70,Long,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,5,77,8485,2011-02-22 00:00:00,47,Balanced,NaN,Little,52,Mixed,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover
5,6,77,8485,2012-02-22 00:00:00,58,Balanced,NaN,Little,62,Mixed,...,55,Normal,Organised,40,Medium,40,Press,60,Normal,Cover
6,7,77,8485,2013-09-20 00:00:00,62,Balanced,NaN,Little,45,Mixed,...,55,Normal,Organised,42,Medium,42,Press,60,Normal,Cover
7,8,77,8485,2014-09-19 00:00:00,58,Balanced,64.0,Normal,62,Mixed,...,57,Normal,Organised,41,Medium,42,Press,60,Normal,Cover
8,9,77,8485,2015-09-10 00:00:00,59,Balanced,64.0,Normal,53,Mixed,...,63,Normal,Free Form,49,Medium,45,Press,63,Normal,Cover
9,10,614,8576,2010-02-22 00:00:00,60,Balanced,NaN,Little,40,Mixed,...,55,Normal,Organised,30,Deep,70,Double,30,Narrow,Offside Trap

In [34]:
Match

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
5,6,1,1,2008/2009,1,2008-09-24 00:00:00,492478,8203,8342,1,...,1.67,4.35,3.40,1.70,4.50,3.40,1.70,NaN,NaN,NaN
6,7,1,1,2008/2009,1,2008-08-16 00:00:00,492479,9999,8571,2,...,3.60,2.10,3.25,3.00,1.85,3.25,3.75,2.10,3.25,3.10
7,8,1,1,2008/2009,1,2008-08-16 00:00:00,492480,4049,9996,1,...,2.40,2.80,3.25,2.25,2.80,3.20,2.25,2.88,3.25,2.20
8,9,1,1,2008/2009,1,2008-08-16 00:00:00,492481,10001,9986,1,...,3.10,2.25,3.25,2.80,2.20,3.30,2.80,2.25,3.20,2.80
9,10,1,1,2008/2009,10,2008-11-01 00:00:00,492564,8342,8571,4,...,10.00,1.30,4.35,8.50,1.25,5.00,10.00,1.29,4.50,9.00
10,11,1,1,2008/2009,10,2008-10-31 00:00:00,492565,9985,9986,1,...,10.00,1.28,4.50,8.50,1.25,5.00,10.00,1.25,5.00,9.00
11,12,1,1,2008/2009,10,2008-11-02 00:00:00,492566,10000,9991,0,...,2.50,2.65,3.30,2.30,2.60,3.25,2.50,2.62,3.20,2.38
12,13,1,1,2008/2009,10,2008-11-01 00:00:00,492567,9994,9998,0,...,4.25,2.00,3.20,3.40,1.85,3.30,4.00,1.83,3.30,3.80
13,14,1,1,2008/2009,10,2008-11-01 00:00:00,492568,7947,10001,2,...,2.38,2.75,3.20,2.30,2.75,3.25,2.35,2.75,3.20,2.30
14,15,1,1,2008/2009,10,2008-11-01 00:00:00,492569,8203,9999,1,...,4.75,1.70,3.40,4.35,1.75,3.40,4.25,1.70,3.40,4.33
15,16,1,1,2008/2009,10,2008-11-01 00:00:00,492570,9996,9984,0,...,2.88,2.20,3.25,2.90,2.30,3.25,2.85,2.30,3.20,2.75
16,17,1,1,2008/2009,10,2008-11-01 00:00:00,492571,4049,9987,1,...,1.62,5.50,3.50,1.55,5.25,3.60,1.60,6.00,3.60,1.50
17,18,1,1,2008/2009,10,2008-11-02 00:00:00,492572,9993,8635,1,...,1.80,3.60,3.25,1.90,4.10,3.40,1.80,3.80,3.30,1.83
18,19,1,1,2008/2009,11,2008-11-08 00:00:00,492573,8635,9994,2,...,9.00,1.28,4.50,8.50,1.30,4.75,7.50,1.30,4.50,8.50
19,20,1,1,2008/2009,11,2008-11-08 00:00:00,492574,9998,9996,0,...,2.75,2.35,3.25,2.65,2.30,3.20,2.75,2.30,3.25,2.70
20,21,1,1,2008/2009,11,2008-11-09 00:00:00,492575,9986,8342,2,...,2.10,3.25,3.25,2.00,3.10,3.20,2.15,3.10,3.25,2.10
21,22,1,1,2008/2009,11,2008-11-07 00:00:00,492576,9984,10000,2,...,4.25,1.75,3.25,4.35,1.80,3.30,4.20,1.70,3.30,4.50
22,23,1,1,2008/2009,11,2008-11-08 00:00:00,492577,9991,7947,1,...,7.00,1.35,4.00,7.50,1.40,4.20,7.00,1.36,4.20,7.00
23,24,1,1,2008/2009,11,2008-11-08 00:00:00,492578,9999,4049,1,...,4.00,1.80,3.25,4.00,1.85,3.30,4.00,1.80,3.30,4.00
24,25,1,1,2008/2009,11,2008-11-08 00:00:00,492579,8571,8203,0,...,3.50,2.00,3.25,3.25,1.95,3.20,3.50,2.00,3.25,3.30
25,26,1,1,2008/2009,11,2008-11-08 00:00:00,492580,10001,9987,1,...,2.60,2.40,3.25,2.60,2.50,3.25,2.50,2.50,3.20,2.50
26,27,1,1,2008/2009,11,2008-11-09 00:00:00,492581,9993,9985,1,...,1.95,3.75,3.25,1.85,3.60,3.25,1.95,3.50,3.30,1.91
27,28,1,1,2008/2009,12,2008-11-16 00:00:00,492582,8342,8635,1,...,3.30,2.25,3.10,2.80,2.10,3.20,3.20,2.20,3.20,2.90
28,29,1,1,2008/2009,12,2008-11-15 00:00:00,492583,9987,9999,1,...,10.00,1.25,5.00,9.00,1.27,5.00,8.50,1.25,5.00,9.00
29,30,1,1,2008/2009,12,2008-11-15 00:00:00,492584,10000,9993,2,...,3.40,2.10,3.30,3.10,2.00,3.20,3.50,2.00,3.25,3.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25949,25950,24558,24558,2015/2016,4,2015-08-08 00:00:00,1992066,9956,7896,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25950,25951,24558,24558,2015/2016,4,2015-08-08 00:00:00,1992067,10199,9931,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25951,25952,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992068,10190,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25952,25953,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992069,9824,10179,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25953,25954,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992070,10192,10191,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25954,25955,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992071,9931,10191,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25955,25956,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992072,10192,7896,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25956,25957,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992073,10199,10190,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25957,25958,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992074,10179,10243,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25958,25959,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992075,9824,9956,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25959,25960,24558,24558,2015/2016,6,2015-08-22 00:00:00,1992076,7896,9931,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25960,25961,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992077,10179,10192,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25961,25962,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992078,10190,9956,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25962,25963,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992079,10191,9824,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25963,25964,24558,24558,2015/2016,6,2015-08-22 00:00:00,1992080,10243,10199,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25964,25965,24558,24558,2015/2016,7,2015-08-29 00:00:00,1992081,7896,10199,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25965,25966,24558,24558,2015/2016,7,2015-08-29 00:00:00,1992082,9824,10190,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25966,25967,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992083,10191,10179,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25967,25968,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992084,9931,10243,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25968,25969,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992085,9956,10192,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25969,25970,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992086,9931,10190,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25970,25971,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992087,10192,9824,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25971,25972,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992088,10199,9956,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25972,25973,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992089,10243,10191,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25973,25974,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992090,10179,7896,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
Match.sort_values("id", inplace = True) 
Match.drop_duplicates(subset ="id", keep = False, inplace = True)

In [9]:
Match.describe()

,id,country_id,league_id,stage,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
count,25979.000000,25979.000000,25979.000000,25979.000000,2.597900e+04,25979.000000,25979.000000,25979.000000,25979.000000,24158.000000,...,17097.000000,22568.000000,22568.000000,22568.000000,14162.000000,14162.000000,14162.000000,14161.000000,14161.000000,14161.000000
mean,12990.000000,11738.630317,11738.630317,18.242773,1.195429e+06,9984.371993,9984.475115,1.544594,1.160938,0.999586,...,4.622343,2.668107,3.899048,4.840281,2.498764,3.648189,4.353097,2.497894,3.660742,4.405663
std,7499.635658,7553.936759,7553.936759,10.407354,4.946279e+05,14087.453758,14087.445135,1.297158,1.142110,0.022284,...,3.632164,1.928753,1.248221,4.318338,1.489299,0.867440,3.010189,1.507793,0.868272,3.189814
min,1.000000,1.000000,1.000000,1.000000,4.831290e+05,1601.000000,1601.000000,0.000000,0.000000,0.000000,...,1.100000,1.030000,1.620000,1.080000,1.050000,1.450000,1.120000,1.040000,1.330000,1.120000
25%,6495.500000,4769.000000,4769.000000,9.000000,7.684365e+05,8475.000000,8475.000000,1.000000,0.000000,1.000000,...,2.500000,1.700000,3.300000,2.550000,1.670000,3.200000,2.500000,1.670000,3.250000,2.500000
50%,12990.000000,10257.000000,10257.000000,18.000000,1.147511e+06,8697.000000,8697.000000,1.000000,1.000000,1.000000,...,3.500000,2.150000,3.500000,3.500000,2.100000,3.300000,3.400000,2.100000,3.400000,3.400000
75%,19484.500000,17642.000000,17642.000000,27.000000,1.709852e+06,9925.000000,9925.000000,2.000000,2.000000,1.000000,...,5.250000,2.800000,4.000000,5.400000,2.650000,3.750000,5.000000,2.620000,3.750000,5.000000
max,25979.000000,24558.000000,24558.000000,38.000000,2.216672e+06,274581.000000,274581.000000,10.000000,9.000000,2.000000,...,41.000000,36.000000,26.000000,67.000000,21.000000,11.000000,34.000000,17.000000,13.000000,34.000000

In [10]:
# iterating the columns 
for col in Match.columns: 
    print(col)

id
country_id
league_id
season
stage
date
match_api_id
home_team_api_id
away_team_api_id
home_team_goal
away_team_goal
home_player_X1
home_player_X2
home_player_X3
home_player_X4
home_player_X5
home_player_X6
home_player_X7
home_player_X8
home_player_X9
home_player_X10
home_player_X11
away_player_X1
away_player_X2
away_player_X3
away_player_X4
away_player_X5
away_player_X6
away_player_X7
away_player_X8
away_player_X9
away_player_X10
away_player_X11
home_player_Y1
home_player_Y2
home_player_Y3
home_player_Y4
home_player_Y5
home_player_Y6
home_player_Y7
home_player_Y8
home_player_Y9
home_player_Y10
home_player_Y11
away_player_Y1
away_player_Y2
away_player_Y3
away_player_Y4
away_player_Y5
away_player_Y6
away_player_Y7
away_player_Y8
away_player_Y9
away_player_Y10
away_player_Y11
home_player_1
home_player_2
home_player_3
home_player_4
home_player_5
home_player_6
home_player_7
home_player_8
home_player_9
home_player_10
home_player_11
away_player_1
away_player_2
away_player_3
away_player_4
away_player_5
away_player_6
away_player_7
away_player_8
away_player_9
away_player_10
away_player_11
goal
shoton
shotoff
foulcommit
card
cross
corner
possession
B365H
B365D
B365A
BWH
BWD
BWA
IWH
IWD
IWA
LBH
LBD
LBA
PSH
PSD
PSA
WHH
WHD
WHA
SJH
SJD
SJA
VCH
VCD
VCA
GBH
GBD
GBA
BSH
BSD
BSA

In [11]:
Match.columns[Match.isnull().any()]

Index(['home_player_X1', 'home_player_X2', 'home_player_X3', 'home_player_X4',
       'home_player_X5', 'home_player_X6', 'home_player_X7', 'home_player_X8',
       'home_player_X9', 'home_player_X10',
       ...
       'SJA', 'VCH', 'VCD', 'VCA', 'GBH', 'GBD', 'GBA', 'BSH', 'BSD', 'BSA'],
      dtype='object', length=104)

In [12]:
country.columns[country.isnull().any()]

Index([], dtype='object')

In [13]:
League.columns[League.isnull().any()]

Index([], dtype='object')

In [14]:
Player.columns[Player.isnull().any()]

Index([], dtype='object')

In [15]:
Player_Attributes.columns[Player_Attributes.isnull().any()]

Index(['overall_rating', 'potential', 'preferred_foot', 'attacking_work_rate',
       'defensive_work_rate', 'crossing', 'finishing', 'heading_accuracy',
       'short_passing', 'volleys', 'dribbling', 'curve', 'free_kick_accuracy',
       'long_passing', 'ball_control', 'acceleration', 'sprint_speed',
       'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina',
       'strength', 'long_shots', 'aggression', 'interceptions', 'positioning',
       'vision', 'penalties', 'marking', 'standing_tackle', 'sliding_tackle',
       'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning',
       'gk_reflexes'],
      dtype='object')

In [16]:
Team_Attributes.columns[Team_Attributes.isnull().any()]

Index(['buildUpPlayDribbling'], dtype='object')

In [17]:
Team.columns[Team.isnull().any()]

Index(['team_fifa_api_id'], dtype='object')

In [18]:
df = pd.merge(Team, Team_Attributes, on='team_api_id',how = 'outer')
df

,id_x,team_api_id,team_fifa_api_id_x,team_long_name,team_short_name,id_y,team_fifa_api_id_y,date,buildUpPlaySpeed,buildUpPlaySpeedClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,1,9987,673.0,KRC Genk,GEN,485.0,673.0,2010-02-22 00:00:00,45.0,Balanced,...,60.0,Normal,Organised,70.0,High,65.0,Press,70.0,Wide,Cover
1,1,9987,673.0,KRC Genk,GEN,486.0,673.0,2011-02-22 00:00:00,66.0,Balanced,...,51.0,Normal,Organised,48.0,Medium,47.0,Press,54.0,Normal,Offside Trap
2,1,9987,673.0,KRC Genk,GEN,487.0,673.0,2012-02-22 00:00:00,53.0,Balanced,...,56.0,Normal,Organised,47.0,Medium,45.0,Press,55.0,Normal,Cover
3,1,9987,673.0,KRC Genk,GEN,488.0,673.0,2013-09-20 00:00:00,58.0,Balanced,...,56.0,Normal,Organised,47.0,Medium,45.0,Press,55.0,Normal,Cover
4,1,9987,673.0,KRC Genk,GEN,489.0,673.0,2014-09-19 00:00:00,58.0,Balanced,...,56.0,Normal,Organised,47.0,Medium,45.0,Press,55.0,Normal,Cover
5,1,9987,673.0,KRC Genk,GEN,490.0,673.0,2015-09-10 00:00:00,58.0,Balanced,...,56.0,Normal,Organised,36.0,Medium,57.0,Press,70.0,Wide,Cover
6,2,9993,675.0,Beerschot AC,BAC,149.0,675.0,2010-02-22 00:00:00,35.0,Balanced,...,50.0,Normal,Organised,70.0,High,70.0,Double,70.0,Wide,Cover
7,2,9993,675.0,Beerschot AC,BAC,150.0,675.0,2011-02-22 00:00:00,47.0,Balanced,...,67.0,Lots,Organised,33.0,Deep,34.0,Press,48.0,Normal,Offside Trap
8,2,9993,675.0,Beerschot AC,BAC,151.0,675.0,2012-02-22 00:00:00,55.0,Balanced,...,49.0,Normal,Organised,45.0,Medium,46.0,Press,50.0,Normal,Cover
9,2,9993,675.0,Beerschot AC,BAC,152.0,675.0,2013-09-20 00:00:00,47.0,Balanced,...,49.0,Normal,Organised,45.0,Medium,46.0,Press,67.0,Wide,Cover
10,3,10000,15005.0,SV Zulte-Waregem,ZUL,1453.0,15005.0,2010-02-22 00:00:00,65.0,Balanced,...,50.0,Normal,Organised,70.0,High,60.0,Press,70.0,Wide,Cover
11,3,10000,15005.0,SV Zulte-Waregem,ZUL,1454.0,15005.0,2011-02-22 00:00:00,52.0,Balanced,...,53.0,Normal,Organised,46.0,Medium,48.0,Press,53.0,Normal,Cover
12,3,10000,15005.0,SV Zulte-Waregem,ZUL,1455.0,15005.0,2012-02-22 00:00:00,54.0,Balanced,...,50.0,Normal,Organised,44.0,Medium,55.0,Press,53.0,Normal,Cover
13,3,10000,15005.0,SV Zulte-Waregem,ZUL,1456.0,15005.0,2013-09-20 00:00:00,54.0,Balanced,...,32.0,Little,Organised,44.0,Medium,58.0,Press,37.0,Normal,Cover
14,3,10000,15005.0,SV Zulte-Waregem,ZUL,1457.0,15005.0,2014-09-19 00:00:00,54.0,Balanced,...,32.0,Little,Organised,44.0,Medium,58.0,Press,37.0,Normal,Cover
15,3,10000,15005.0,SV Zulte-Waregem,ZUL,1458.0,15005.0,2015-09-10 00:00:00,54.0,Balanced,...,32.0,Little,Organised,44.0,Medium,58.0,Press,37.0,Normal,Cover
16,4,9994,2007.0,Sporting Lokeren,LOK,759.0,2007.0,2010-02-22 00:00:00,60.0,Balanced,...,50.0,Normal,Organised,65.0,Medium,65.0,Press,70.0,Wide,Cover
17,4,9994,2007.0,Sporting Lokeren,LOK,760.0,2007.0,2011-02-22 00:00:00,66.0,Balanced,...,52.0,Normal,Organised,48.0,Medium,58.0,Press,55.0,Normal,Cover
18,4,9994,2007.0,Sporting Lokeren,LOK,761.0,2007.0,2012-02-22 00:00:00,67.0,Fast,...,50.0,Normal,Organised,45.0,Medium,52.0,Press,52.0,Normal,Cover
19,4,9994,2007.0,Sporting Lokeren,LOK,762.0,2007.0,2013-09-20 00:00:00,67.0,Fast,...,50.0,Normal,Organised,45.0,Medium,52.0,Press,52.0,Normal,Cover
20,4,9994,2007.0,Sporting Lokeren,LOK,763.0,2007.0,2014-09-19 00:00:00,62.0,Balanced,...,62.0,Normal,Organised,45.0,Medium,52.0,Press,52.0,Normal,Cover
21,4,9994,2007.0,Sporting Lokeren,LOK,764.0,2007.0,2015-09-10 00:00:00,62.0,Balanced,...,62.0,Normal,Organised,45.0,Medium,52.0,Press,52.0,Normal,Cover
22,5,9984,1750.0,KSV Cercle Brugge,CEB,295.0,1750.0,2010-02-22 00:00:00,45.0,Balanced,...,55.0,Normal,Organised,65.0,Medium,60.0,Press,70.0,Wide,Cover
23,5,9984,1750.0,KSV Cercle Brugge,CEB,296.0,1750.0,2011-02-22 00:00:00,50.0,Balanced,...,65.0,Normal,Organised,60.0,Medium,50.0,Press,70.0,Wide,Cover
24,5,9984,1750.0,KSV Cercle Brugge,CEB,297.0,1750.0,2012-02-22 00:00:00,68.0,Fast,...,42.0,Normal,Organised,59.0,Medium,47.0,Press,62.0,Normal,Cover
25,5,9984,1750.0,KSV Cercle Brugge,CEB,298.0,1750.0,2013-09-20 00:00:00,53.0,Balanced,...,42.0,Normal,Free Form,59.0,Medium,47.0,Press,62.0,Normal,Cover
26,5,9984,1750.0,KSV Cercle Brugge,CEB,299.0,1750.0,2014-09-19 00:00:00,53.0,Balanced,...,42.0,Normal,Organised,59.0,Medium,47.0,Press,62.0,Normal,Cover
27,5,9984,1750.0,KSV Cercle Brugge,CEB,300.0,1750.0,2015-09-10 00:00:00,53.0,Balanced,...,42.0,Normal,Organised,59.0,Medium,47.0,Press,62.0,Normal,Cover
28,6,8635,229.0,RSC Anderlecht,AND,46.0,229.0,2010-02-22 00:00:00,50.0,Balanced,...,60.0,Normal,Organised,70.0,High,50.0,Press,70.0,Wide,Cover
29,6,8635,229.0,RSC Anderlecht,AND,47.0,229.0,2011-02-22 00:00:00,50.0,Balanced,...,60.0,Normal,Organised,70.0,High,50.0,Press,70.0,Wide,Offside Trap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1439,49121,10199,897.0,FC Luzern,LUZ,775.0,897.0,2014-09-19 00:00:00,63.0,Balanced,...,66.0,Normal,Organised,48.0,Medium,53.0,Press,50.0,Normal,Cover
1440,49121,10199,897.0,FC Luzern,LUZ,776.0,897.0,2015-09-10 00:00:00,63.0,Balanced,...,66.0,Normal,Organised,48.0,Medium,53.0,Press,50.0,Normal,Cover
1441,49122,9824,286.0,FC Vaduz,VAD,445.0,286.0,2015-09-10 00:00:00,53.0,Balanced,...,46.0,Normal,Organised,42.0,Medium,33.0,Contain,58.0,Normal,Cover
1442,49123,7955,435.0,Neuchâtel Xamax,XAM,1427.0,435.0,2010-02-22 00:00:00,60.0,Balanced,...,60.0,Normal,Organised,50.0,Medium,45.0,Press,55.0,Normal,Cover
1443,49123,7955,435.0,Neuchâtel Xamax,XAM,1428.0,435.0,2011-02-22 00:00:00,54.0,Balanced,...,53.0,Normal,Organised,49.0,Medium,45.0,Press,52.0,Normal,Cover
1444,49123,7955,435.0,Neuchâtel Xamax,XAM,1429.0,435.0,2012-02-22 00:00:00,49.0,Balanced,...,34.0,Normal,Organised,34.0,Medium,31.0,Contain,51.0,Normal,Cover
1445,49124,10243,894.0,FC Zürich,ZUR,446.0,894.0,2010-02-22 00:00:00,45.0,Balanced,...,50.0,Normal,Organised,50.0,Medium,55.0,Press,50.0,Normal,Offside Trap
1446,49124,10243,894.0,FC Zürich,ZUR,447.0,894.0,2011-02-22 00:00:00,48.0,Balanced,...,55.0,Normal,Organised,54.0,Medium,49.0,Press,60.0,Normal,Cover
1447,49124,10243,894.0,FC Zürich,ZUR,448.0,894.0,2012-02-22 00:00:00,62.0,Balanced,...,54.0,Normal,Organised,47.0,Medium,43.0,Press,56.0,Normal,Cover
1448,49124,10243,894.0,FC Zürich,ZUR,449.0,894.0,2013-09-20 00:00:00,62.0,Balanced,...,54.0,Normal,Organised,47.0,Medium,43.0,Press,56.0,Normal,Cover
1449,49124,10243,894.0,FC Zürich,ZUR,450.0,894.0,2014-09-19 00:00:00,62.0,Balanced,...,54.0,Normal,Organised,47.0,Medium,43.0,Press,56.0,Normal,Cover
1450,49124,10243,894.0,FC Zürich,ZUR,451.0,894.0,2015-09-10 00:00:00,62.0,Balanced,...,54.0,Normal,Organised,47.0,Medium,43.0,Press,56.0,Normal,Cover
1451,49479,10190,898.0,FC St. Gallen,GAL,1211.0,898.0,2010-02-22 00:00:00,35.0,Balanced,...,55.0,Normal,Organised,50.0,Medium,55.0,Press,50.0,Normal,Cover
1452,49479,10190,898.0,FC St. Gallen,GAL,1212.0,898.0,2011-02-22 00:00:00,47.0,Balanced,...,56.0,Normal,Organised,49.0,Medium,55.0,Press,48.0,Normal,Cover
1453,49479,10190,898.0,FC St. Gallen,GAL,1213.0,898.0,2013-09-20 00:00:00,52.0,Balanced,...,37.0,Normal,Organised,40.0,Medium,41.0,Press,52.0,Normal,Cover
1454,49479,10190,898.0,FC St. Gallen,GAL,1214.0,898.0,2014-09-19 00:00:00,52.0,Balanced,...,37.0,Normal,Organised,40.0,Medium,41.0,Press,52.0,Normal,Cover
1455,49479,10190,898.0,FC St. Gallen,GAL,1215.0,898.0,2015-09-10 00:00:00,52.0,Balanced,...,37.0,Normal,Organised,40.0,Medium,36.0,Press,52.0,Normal,Cover
1456,49837,10191,1715.0,FC Thun,THU,1265.0,1715.0,2011-02-22 00:00:00,51.0,Balanced,...,31.0,Little,Organised,37.0,Medium,34.0,Press,46.0,Normal,Cover
1457,49837,10191,1715.0,FC Thun,THU,1266.0,1715.0,2012-02-22 00:00:00,58.0,Balanced,...,66.0,Normal,Organised,47.0,Medium,45.0,Press,53.0,Normal,Cover
1458,49837,10191,1715.0,FC Thun,THU,1267.0,1715.0,2013-09-20 00:00:00,58.0,Balanced,...,66.0,Normal,Organised,47.0,Medium,45.0,Press,53.0,Normal,Cover
1459,49837,10191,1715.0,FC Thun,THU,1268.0,1715.0,2014-09-19 00:00:00,58.0,Balanced,...,66.0,Normal,Organised,47.0,Medium,45.0,Press,53.0,Normal,Cover
1460,49837,10191,1715.0,FC Thun,THU,1269.0,1715.0,2015-09-10 00:00:00,58.0,Balanced,...,66.0,Normal,Organised,47.0,Medium,45.0,Press,53.0,Normal,Cover
1461,50201,9777,324.0,Servette FC,SER,1154.0,324.0,2010-02-22 00:00:00,30.0,Slow,...,60.0,Normal,Organised,55.0,Medium,60.0,Press,55.0,Normal,Cover
1462,50201,9777,324.0,Servette FC,SER,1155.0,324.0,2012-02-22 00:00:00,48.0,Balanced,...,45.0,Normal,Organised,49.0,Medium,45.0,Press,49.0,Normal,Cover
1463,50201,9777,324.0,Servette FC,SER,1156.0,324.0,2013-09-20 00:00:00,48.0,Balanced,...,45.0,Normal,Organised,49.0,Medium,45.0,Press,49.0,Normal,Cover
1464,50204,7730,1862.0,FC Lausanne-Sports,LAU,672.0,1862.0,2010-02-22 00:00:00,30.0,Slow,...,60.0,Normal,Organised,55.0,Medium,60.0,Press,50.0,Normal,Cover
1465,50204,7730,1862.0,FC Lausanne-Sports,LAU,673.0,1862.0,2012-02-22 00:00:00,37.0,Balanced,...,48.0,Normal,Organised,43.0,Medium,43.0,Press,55.0,Normal,Cover
1466,50204,7730,1862.0,FC Lausanne-Sports,LAU,674.0,1862.0,2013-09-20 00:00:00,51.0,Balanced,...,48.0,Normal,Organised,43.0,Medium,43.0,Press,55.0,Normal,Cover
1467,50204,7730,1862.0,FC Lausanne-Sports,LAU,675.0,1862.0,2014-09-19 00:00:00,37.0,Balanced,...,52.0,Normal,Organised,46.0,Medium,44.0,Press,55.0,Normal,Cover
1468,51606,7896,NaN,Lugano,LUG,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
Match.loc[Match['home_team_api_id'] == 7896]

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
25815,25816,24558,24558,2015/2016,12,2015-10-18 00:00:00,1992107,7896,10190,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25825,25826,24558,24558,2015/2016,14,2015-11-01 00:00:00,1992117,7896,10179,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25830,25831,24558,24558,2015/2016,15,2015-11-07 00:00:00,1992122,7896,10192,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25844,25845,24558,24558,2015/2016,18,2015-12-06 00:00:00,1992136,7896,9956,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25850,25851,24558,24558,2015/2016,19,2016-02-06 00:00:00,1992142,7896,9824,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25856,25857,24558,24558,2015/2016,2,2015-07-26 00:00:00,1992058,7896,10191,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25866,25867,24558,24558,2015/2016,21,2016-02-20 00:00:00,1992153,7896,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25874,25875,24558,24558,2015/2016,23,2016-04-13 00:00:00,1992161,7896,9931,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25890,25891,24558,24558,2015/2016,26,2016-04-03 00:00:00,1992177,7896,10179,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25899,25900,24558,24558,2015/2016,28,2016-04-17 00:00:00,1992186,7896,10191,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25911,25912,24558,24558,2015/2016,3,2015-08-02 00:00:00,1992063,7896,9824,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25921,25922,24558,24558,2015/2016,31,2016-05-01 00:00:00,1992203,7896,10199,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25924,25925,24558,24558,2015/2016,32,2016-05-08 00:00:00,1992206,7896,9956,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25935,25936,24558,24558,2015/2016,34,2016-05-16 00:00:00,1992217,7896,10192,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25945,25946,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992226,7896,10190,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25959,25960,24558,24558,2015/2016,6,2015-08-22 00:00:00,1992076,7896,9931,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25964,25965,24558,24558,2015/2016,7,2015-08-29 00:00:00,1992081,7896,10199,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
Match.loc[Match['away_team_api_id'] == 7896]

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
25802,25803,24558,24558,2015/2016,1,2015-07-19 00:00:00,1992055,10190,7896,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25804,25805,24558,24558,2015/2016,10,2015-09-26 00:00:00,1992096,9931,7896,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25809,25810,24558,24558,2015/2016,11,2015-10-03 00:00:00,1992101,10199,7896,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25822,25823,24558,24558,2015/2016,13,2015-10-25 00:00:00,1992114,10191,7896,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25838,25839,24558,24558,2015/2016,16,2015-11-22 00:00:00,1992130,10243,7896,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25842,25843,24558,24558,2015/2016,17,2015-11-28 00:00:00,1992134,9824,7896,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25862,25863,24558,24558,2015/2016,20,2016-02-13 00:00:00,1992149,10191,7896,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25870,25871,24558,24558,2015/2016,22,2016-02-28 00:00:00,1992157,10190,7896,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25881,25882,24558,24558,2015/2016,24,2016-03-12 00:00:00,1992168,10199,7896,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25884,25885,24558,24558,2015/2016,25,2016-03-20 00:00:00,1992171,9956,7896,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25898,25899,24558,24558,2015/2016,27,2016-04-09 00:00:00,1992185,10192,7896,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25904,25905,24558,24558,2015/2016,29,2016-04-20 00:00:00,1992191,9931,7896,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25916,25917,24558,24558,2015/2016,30,2016-04-23 00:00:00,1992198,10179,7896,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25933,25934,24558,24558,2015/2016,33,2016-05-11 00:00:00,1992215,10243,7896,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25941,25942,24558,24558,2015/2016,35,2016-05-22 00:00:00,1992223,9824,7896,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25949,25950,24558,24558,2015/2016,4,2015-08-08 00:00:00,1992066,9956,7896,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25955,25956,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992072,10192,7896,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25973,25974,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992090,10179,7896,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
Match_new = Match[Match.away_team_api_id != 7896]
Match_new = Match_new[Match_new.home_team_api_id != 7896]
Match_new

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
5,6,1,1,2008/2009,1,2008-09-24 00:00:00,492478,8203,8342,1,...,1.67,4.35,3.40,1.70,4.50,3.40,1.70,NaN,NaN,NaN
6,7,1,1,2008/2009,1,2008-08-16 00:00:00,492479,9999,8571,2,...,3.60,2.10,3.25,3.00,1.85,3.25,3.75,2.10,3.25,3.10
7,8,1,1,2008/2009,1,2008-08-16 00:00:00,492480,4049,9996,1,...,2.40,2.80,3.25,2.25,2.80,3.20,2.25,2.88,3.25,2.20
8,9,1,1,2008/2009,1,2008-08-16 00:00:00,492481,10001,9986,1,...,3.10,2.25,3.25,2.80,2.20,3.30,2.80,2.25,3.20,2.80
9,10,1,1,2008/2009,10,2008-11-01 00:00:00,492564,8342,8571,4,...,10.00,1.30,4.35,8.50,1.25,5.00,10.00,1.29,4.50,9.00
10,11,1,1,2008/2009,10,2008-10-31 00:00:00,492565,9985,9986,1,...,10.00,1.28,4.50,8.50,1.25,5.00,10.00,1.25,5.00,9.00
11,12,1,1,2008/2009,10,2008-11-02 00:00:00,492566,10000,9991,0,...,2.50,2.65,3.30,2.30,2.60,3.25,2.50,2.62,3.20,2.38
12,13,1,1,2008/2009,10,2008-11-01 00:00:00,492567,9994,9998,0,...,4.25,2.00,3.20,3.40,1.85,3.30,4.00,1.83,3.30,3.80
13,14,1,1,2008/2009,10,2008-11-01 00:00:00,492568,7947,10001,2,...,2.38,2.75,3.20,2.30,2.75,3.25,2.35,2.75,3.20,2.30
14,15,1,1,2008/2009,10,2008-11-01 00:00:00,492569,8203,9999,1,...,4.75,1.70,3.40,4.35,1.75,3.40,4.25,1.70,3.40,4.33
15,16,1,1,2008/2009,10,2008-11-01 00:00:00,492570,9996,9984,0,...,2.88,2.20,3.25,2.90,2.30,3.25,2.85,2.30,3.20,2.75
16,17,1,1,2008/2009,10,2008-11-01 00:00:00,492571,4049,9987,1,...,1.62,5.50,3.50,1.55,5.25,3.60,1.60,6.00,3.60,1.50
17,18,1,1,2008/2009,10,2008-11-02 00:00:00,492572,9993,8635,1,...,1.80,3.60,3.25,1.90,4.10,3.40,1.80,3.80,3.30,1.83
18,19,1,1,2008/2009,11,2008-11-08 00:00:00,492573,8635,9994,2,...,9.00,1.28,4.50,8.50,1.30,4.75,7.50,1.30,4.50,8.50
19,20,1,1,2008/2009,11,2008-11-08 00:00:00,492574,9998,9996,0,...,2.75,2.35,3.25,2.65,2.30,3.20,2.75,2.30,3.25,2.70
20,21,1,1,2008/2009,11,2008-11-09 00:00:00,492575,9986,8342,2,...,2.10,3.25,3.25,2.00,3.10,3.20,2.15,3.10,3.25,2.10
21,22,1,1,2008/2009,11,2008-11-07 00:00:00,492576,9984,10000,2,...,4.25,1.75,3.25,4.35,1.80,3.30,4.20,1.70,3.30,4.50
22,23,1,1,2008/2009,11,2008-11-08 00:00:00,492577,9991,7947,1,...,7.00,1.35,4.00,7.50,1.40,4.20,7.00,1.36,4.20,7.00
23,24,1,1,2008/2009,11,2008-11-08 00:00:00,492578,9999,4049,1,...,4.00,1.80,3.25,4.00,1.85,3.30,4.00,1.80,3.30,4.00
24,25,1,1,2008/2009,11,2008-11-08 00:00:00,492579,8571,8203,0,...,3.50,2.00,3.25,3.25,1.95,3.20,3.50,2.00,3.25,3.30
25,26,1,1,2008/2009,11,2008-11-08 00:00:00,492580,10001,9987,1,...,2.60,2.40,3.25,2.60,2.50,3.25,2.50,2.50,3.20,2.50
26,27,1,1,2008/2009,11,2008-11-09 00:00:00,492581,9993,9985,1,...,1.95,3.75,3.25,1.85,3.60,3.25,1.95,3.50,3.30,1.91
27,28,1,1,2008/2009,12,2008-11-16 00:00:00,492582,8342,8635,1,...,3.30,2.25,3.10,2.80,2.10,3.20,3.20,2.20,3.20,2.90
28,29,1,1,2008/2009,12,2008-11-15 00:00:00,492583,9987,9999,1,...,10.00,1.25,5.00,9.00,1.27,5.00,8.50,1.25,5.00,9.00
29,30,1,1,2008/2009,12,2008-11-15 00:00:00,492584,10000,9993,2,...,3.40,2.10,3.30,3.10,2.00,3.20,3.50,2.00,3.25,3.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25942,25943,24558,24558,2015/2016,35,2016-05-22 00:00:00,1992224,10192,9931,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25943,25944,24558,24558,2015/2016,35,2016-05-22 00:00:00,1992234,10190,10199,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25944,25945,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992225,9931,9956,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25946,25947,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992227,10199,10179,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25947,25948,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992228,10191,10192,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25948,25949,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992229,10243,9824,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25950,25951,24558,24558,2015/2016,4,2015-08-08 00:00:00,1992067,10199,9931,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25951,25952,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992068,10190,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25952,25953,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992069,9824,10179,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25953,25954,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992070,10192,10191,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25954,25955,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992071,9931,10191,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25956,25957,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992073,10199,10190,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25957,25958,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992074,10179,10243,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25958,25959,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992075,9824,9956,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25960,25961,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992077,10179,10192,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25961,25962,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992078,10190,9956,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25962,25963,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992079,10191,9824,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25963,25964,24558,24558,2015/2016,6,2015-08-22 00:00:00,1992080,10243,10199,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25965,25966,24558,24558,2015/2016,7,2015-08-29 00:00:00,1992082,9824,10190,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25966,25967,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992083,10191,10179,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25967,25968,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992084,9931,10243,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25968,25969,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992085,9956,10192,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25969,25970,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992086,9931,10190,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25970,25971,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992087,10192,9824,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25971,25972,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992088,10199,9956,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25972,25973,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992089,10243,10191,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
nans = Player_Attributes.loc[Player_Attributes.isnull().any(axis=1)]
nans

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
373,374,156626,46447,2010-08-30 00:00:00,64.0,71.0,right,None,_0,41.0,...,61.0,39.0,62.0,61.0,57.0,15.0,14.0,13.0,10.0,12.0
374,375,156626,46447,2010-02-22 00:00:00,64.0,71.0,right,None,_0,41.0,...,61.0,58.0,62.0,61.0,57.0,6.0,20.0,45.0,20.0,20.0
375,376,156626,46447,2008-08-30 00:00:00,66.0,71.0,right,None,_0,41.0,...,61.0,58.0,67.0,61.0,57.0,6.0,20.0,45.0,20.0,20.0
376,377,156626,46447,2007-08-30 00:00:00,68.0,75.0,right,None,_0,41.0,...,61.0,58.0,69.0,64.0,57.0,6.0,20.0,45.0,20.0,20.0
377,378,156626,46447,2007-02-22 00:00:00,66.0,65.0,right,None,_0,41.0,...,61.0,55.0,66.0,63.0,57.0,6.0,9.0,45.0,13.0,10.0
392,393,202425,245653,2011-02-22 00:00:00,64.0,69.0,left,None,_0,47.0,...,52.0,42.0,64.0,65.0,62.0,11.0,5.0,15.0,10.0,10.0
393,394,202425,245653,2007-02-22 00:00:00,64.0,69.0,left,None,_0,47.0,...,52.0,42.0,64.0,65.0,62.0,11.0,5.0,15.0,10.0,10.0
446,447,52782,38423,2010-02-22 00:00:00,68.0,70.0,right,None,_0,60.0,...,NaN,47.0,52.0,50.0,NaN,7.0,20.0,62.0,20.0,20.0
447,448,52782,38423,2009-08-30 00:00:00,68.0,70.0,right,None,_0,60.0,...,NaN,47.0,52.0,50.0,NaN,7.0,20.0,62.0,20.0,20.0
448,449,52782,38423,2008-08-30 00:00:00,68.0,69.0,right,None,_0,60.0,...,NaN,47.0,52.0,50.0,NaN,7.0,20.0,62.0,20.0,20.0
449,450,52782,38423,2007-08-30 00:00:00,70.0,69.0,right,None,_0,60.0,...,NaN,47.0,52.0,50.0,NaN,7.0,20.0,62.0,20.0,20.0
450,451,52782,38423,2007-02-22 00:00:00,70.0,69.0,right,None,_0,60.0,...,NaN,47.0,72.0,70.0,NaN,7.0,7.0,62.0,12.0,5.0
451,452,51868,3264,2010-08-30 00:00:00,62.0,73.0,right,None,_0,49.0,...,66.0,41.0,30.0,34.0,36.0,13.0,7.0,7.0,9.0,13.0
452,453,51868,3264,2010-02-22 00:00:00,62.0,73.0,right,None,_0,49.0,...,66.0,62.0,30.0,34.0,36.0,11.0,20.0,27.0,20.0,20.0
453,454,51868,3264,2009-08-30 00:00:00,62.0,73.0,right,None,_0,49.0,...,66.0,62.0,30.0,34.0,36.0,11.0,20.0,27.0,20.0,20.0
454,455,51868,3264,2008-08-30 00:00:00,61.0,73.0,right,None,_0,49.0,...,66.0,62.0,30.0,34.0,36.0,11.0,20.0,27.0,20.0,20.0
455,456,51868,3264,2007-02-22 00:00:00,61.0,73.0,right,None,_0,49.0,...,66.0,62.0,30.0,34.0,36.0,11.0,20.0,27.0,20.0,20.0
478,479,33022,31684,2009-08-30 00:00:00,73.0,76.0,right,None,_0,56.0,...,NaN,68.0,76.0,75.0,NaN,5.0,23.0,71.0,23.0,23.0
479,480,33022,31684,2009-02-22 00:00:00,77.0,79.0,right,None,_0,68.0,...,NaN,69.0,83.0,78.0,NaN,5.0,23.0,76.0,23.0,23.0
480,481,33022,31684,2008-08-30 00:00:00,77.0,80.0,right,None,_0,68.0,...,NaN,69.0,83.0,78.0,NaN,5.0,23.0,76.0,23.0,23.0
481,482,33022,31684,2007-08-30 00:00:00,78.0,79.0,right,None,_0,72.0,...,NaN,69.0,80.0,76.0,NaN,5.0,23.0,76.0,23.0,23.0
482,483,33022,31684,2007-02-22 00:00:00,78.0,79.0,right,None,_0,72.0,...,NaN,69.0,80.0,76.0,NaN,5.0,10.0,76.0,10.0,7.0
483,484,33022,31684,2007-02-22 00:00:00,NaN,NaN,None,None,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484,485,177295,32637,2010-02-22 00:00:00,61.0,65.0,right,None,_0,42.0,...,NaN,66.0,22.0,27.0,NaN,7.0,20.0,35.0,20.0,20.0
485,486,177295,32637,2009-08-30 00:00:00,56.0,65.0,right,None,_0,42.0,...,NaN,47.0,22.0,27.0,NaN,7.0,20.0,35.0,20.0,20.0
486,487,177295,32637,2009-02-22 00:00:00,66.0,76.0,right,None,_0,42.0,...,NaN,47.0,22.0,27.0,NaN,7.0,20.0,35.0,20.0,20.0
487,488,177295,32637,2008-08-30 00:00:00,66.0,76.0,right,None,_0,42.0,...,NaN,47.0,22.0,27.0,NaN,7.0,20.0,35.0,20.0,20.0
488,489,177295,32637,2007-08-30 00:00:00,72.0,76.0,right,None,_0,42.0,...,NaN,47.0,22.0,27.0,NaN,7.0,20.0,35.0,20.0,20.0
489,490,177295,32637,2007-02-22 00:00:00,59.0,70.0,right,None,_0,42.0,...,NaN,47.0,22.0,27.0,NaN,7.0,6.0,35.0,7.0,4.0
983,984,111085,29904,2007-02-22 00:00:00,NaN,NaN,None,None,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183445,183446,139083,25906,2009-08-30 00:00:00,72.0,74.0,right,None,3,72.0,...,NaN,74.0,41.0,36.0,NaN,8.0,23.0,68.0,23.0,23.0
183446,183447,139083,25906,2009-02-22 00:00:00,73.0,75.0,right,None,3,73.0,...,NaN,76.0,41.0,36.0,NaN,8.0,23.0,67.0,23.0,23.0
183447,183448,139083,25906,2008-08-30 00:00:00,74.0,75.0,right,None,3,73.0,...,NaN,76.0,41.0,36.0,NaN,8.0,23.0,67.0,23.0,23.0
183448,183449,139083,25906,2007-08-30 00:00:00,74.0,75.0,right,None,3,73.0,...,NaN,76.0,41.0,36.0,NaN,8.0,23.0,67.0,23.0,23.0
183449,183450,139083,25906,2007-02-22 00:00:00,73.0,77.0,right,None,3,73.0,...,NaN,64.0,41.0,36.0,NaN,8.0,6.0,65.0,10.0,9.0
183487,183488,28765,38843,2007-02-22 00:00:00,NaN,NaN,None,None,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183488,183489,177901,45308,2010-02-22 00:00:00,58.0,64.0,right,None,_0,38.0,...,NaN,66.0,51.0,52.0,NaN,10.0,20.0,48.0,20.0,20.0
183489,183490,177901,45308,2009-08-30 00:00:00,61.0,65.0,right,None,_0,39.0,...,NaN,67.0,52.0,53.0,NaN,10.0,20.0,49.0,20.0,20.0
183490,183491,177901,45308,2008-08-30 00:00:00,61.0,65.0,right,None,_0,39.0,...,NaN,67.0,52.0,53.0,NaN,10.0,20.0,49.0,20.0,20.0
183491,183492,177901,45308,2007-08-30 00:00:00,64.0,65.0,right,None,_0,41.0,...,NaN,69.0,54.0,55.0,NaN,10.0,20.0,51.0,20.0,20.0
183492,183493,177901,45308,2007-02-22 00:00:00,64.0,65.0,right,None,_0,41.0,...,NaN,69.0,54.0,55.0,NaN,10.0,20.0,51.0,20.0,20.0
183535,183536,51883,30850,2009-02-22 00:00:00,73.0,81.0,right,None,o,20.0,...,NaN,70.0,20.0,20.0,NaN,75.0,73.0,71.0,73.0,75.0
183536,183537,51883,30850,2008-08-30 00:00:00,77.0,81.0,right,None,o,20.0,...,NaN,70.0,20.0,20.0,NaN,82.0,75.0,78.0,73.0,78.0
183537,183538,51883,30850,2007-08-30 00:00:00,70.0,80.0,right,None,o,40.0,...,NaN,56.0,22.0,51.0,NaN,74.0,70.0,73.0,72.0,71.0
183538,183539,51883,30850,2007-02-22 00:00:00,70.0,80.0,right,None,o,40.0,...,NaN,56.0,22.0,51.0,NaN,74.0,70.0,73.0,72.0,71.0
183953,183954,111191,36491,2011-02-22 00:00:00,68.0,73.0,left,None,_0,64.0,...,66.0,61.0,67.0,71.0,59.0,15.0,13.0,5.0,6.0,6.0
183954,183955,111191,36491,2010-08-30 00:00:00,68.0,73.0,left,None,_0,64.0,...,66.0,61.0,71.0,71.0,59.0,15.0,13.0,5.0,6.0,6.0
183955,183956,111191,36491,2009-08-30 00:00:00,68.0,74.0,left,None,_0,64.0,...,66.0,61.0,71.0,71.0,59.0,4.0,21.0,61.0,21.0,21.0
183956,183957,111191,36491,2009-02-22 00:00:00,68.0,74.0,left,None,_0,64.0,...,66.0,61.0,71.0,71.0,59.0,4.0,21.0,61.0,21.0,21.0
183957,183958,111191,36491,2008-08-30 00:00:00,67.0,72.0,left,None,_0,62.0,...,66.0,61.0,61.0,62.0,59.0,4.0,21.0,61.0,21.0,21.0
183958,183959,111191,36491,2007-08-30 00:00:00,67.0,72.0,left,None,_0,62.0,...,66.0,61.0,43.0,52.0,59.0,4.0,21.0,52.0,21.0,21.0
183959,183960,111191,36491,2007-02-22 00:00:00,67.0,72.0,left,None,_0,62.0,...,66.0,61.0,43.0,52.0,59.0,4.0,21.0,52.0,21.0,21.0
183960,183961,47058,35506,2011-02-22 00:00:00,67.0,78.0,right,None,_0,48.0,...,63.0,45.0,65.0,66.0,65.0,14.0,7.0,15.0,10.0,12.0
183961,183962,47058,35506,2010-08-30 00:00:00,67.0,78.0,right,None,_0,48.0,...,63.0,45.0,65.0,66.0,65.0,14.0,7.0,15.0,10.0,12.0
183962,183963,47058,35506,2010-02-22 00:00:00,67.0,78.0,right,None,_0,48.0,...,63.0,70.0,65.0,66.0,65.0,14.0,25.0,51.0,25.0,25.0
183963,183964,47058,35506,2009-08-30 00:00:00,70.0,78.0,right,None,_0,48.0,...,63.0,70.0,70.0,74.0,65.0,14.0,25.0,51.0,25.0,25.0
183964,183965,47058,35506,2009-02-22 00:00:00,70.0,78.0,right,None,_0,48.0,...,63.0,70.0,70.0,74.0,65.0,14.0,25.0,51.0,25.0,25.0
183965,183966,47058,35506,2008-08-30 00:00:00,72.0,78.0,right,None,_0,48.0,...,63.0,70.0,76.0,78.0,65.0,14.0,25.0,51.0,25.0,25.0
183966,183967,47058,35506,2007-08-30 00:00:00,75.0,78.0,right,None,_0,48.0,...,63.0,70.0,76.0,78.0,65.0,14.0,25.0,51.0,25.0,25.0
183967,183968,47058,35506,2007-02-22 00:00:00,78.0,79.0,right,None,_0,38.0,...,63.0,72.0,79.0,84.0,65.0,14.0,9.0,48.0,7.0,11.0

In [23]:
tmp = Match.loc[Match.isnull().any(axis=1)]
tmp

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
5,6,1,1,2008/2009,1,2008-09-24 00:00:00,492478,8203,8342,1,...,1.67,4.35,3.40,1.70,4.50,3.40,1.70,NaN,NaN,NaN
6,7,1,1,2008/2009,1,2008-08-16 00:00:00,492479,9999,8571,2,...,3.60,2.10,3.25,3.00,1.85,3.25,3.75,2.10,3.25,3.10
7,8,1,1,2008/2009,1,2008-08-16 00:00:00,492480,4049,9996,1,...,2.40,2.80,3.25,2.25,2.80,3.20,2.25,2.88,3.25,2.20
8,9,1,1,2008/2009,1,2008-08-16 00:00:00,492481,10001,9986,1,...,3.10,2.25,3.25,2.80,2.20,3.30,2.80,2.25,3.20,2.80
9,10,1,1,2008/2009,10,2008-11-01 00:00:00,492564,8342,8571,4,...,10.00,1.30,4.35,8.50,1.25,5.00,10.00,1.29,4.50,9.00
10,11,1,1,2008/2009,10,2008-10-31 00:00:00,492565,9985,9986,1,...,10.00,1.28,4.50,8.50,1.25,5.00,10.00,1.25,5.00,9.00
11,12,1,1,2008/2009,10,2008-11-02 00:00:00,492566,10000,9991,0,...,2.50,2.65,3.30,2.30,2.60,3.25,2.50,2.62,3.20,2.38
12,13,1,1,2008/2009,10,2008-11-01 00:00:00,492567,9994,9998,0,...,4.25,2.00,3.20,3.40,1.85,3.30,4.00,1.83,3.30,3.80
13,14,1,1,2008/2009,10,2008-11-01 00:00:00,492568,7947,10001,2,...,2.38,2.75,3.20,2.30,2.75,3.25,2.35,2.75,3.20,2.30
14,15,1,1,2008/2009,10,2008-11-01 00:00:00,492569,8203,9999,1,...,4.75,1.70,3.40,4.35,1.75,3.40,4.25,1.70,3.40,4.33
15,16,1,1,2008/2009,10,2008-11-01 00:00:00,492570,9996,9984,0,...,2.88,2.20,3.25,2.90,2.30,3.25,2.85,2.30,3.20,2.75
16,17,1,1,2008/2009,10,2008-11-01 00:00:00,492571,4049,9987,1,...,1.62,5.50,3.50,1.55,5.25,3.60,1.60,6.00,3.60,1.50
17,18,1,1,2008/2009,10,2008-11-02 00:00:00,492572,9993,8635,1,...,1.80,3.60,3.25,1.90,4.10,3.40,1.80,3.80,3.30,1.83
18,19,1,1,2008/2009,11,2008-11-08 00:00:00,492573,8635,9994,2,...,9.00,1.28,4.50,8.50,1.30,4.75,7.50,1.30,4.50,8.50
19,20,1,1,2008/2009,11,2008-11-08 00:00:00,492574,9998,9996,0,...,2.75,2.35,3.25,2.65,2.30,3.20,2.75,2.30,3.25,2.70
20,21,1,1,2008/2009,11,2008-11-09 00:00:00,492575,9986,8342,2,...,2.10,3.25,3.25,2.00,3.10,3.20,2.15,3.10,3.25,2.10
21,22,1,1,2008/2009,11,2008-11-07 00:00:00,492576,9984,10000,2,...,4.25,1.75,3.25,4.35,1.80,3.30,4.20,1.70,3.30,4.50
22,23,1,1,2008/2009,11,2008-11-08 00:00:00,492577,9991,7947,1,...,7.00,1.35,4.00,7.50,1.40,4.20,7.00,1.36,4.20,7.00
23,24,1,1,2008/2009,11,2008-11-08 00:00:00,492578,9999,4049,1,...,4.00,1.80,3.25,4.00,1.85,3.30,4.00,1.80,3.30,4.00
24,25,1,1,2008/2009,11,2008-11-08 00:00:00,492579,8571,8203,0,...,3.50,2.00,3.25,3.25,1.95,3.20,3.50,2.00,3.25,3.30
25,26,1,1,2008/2009,11,2008-11-08 00:00:00,492580,10001,9987,1,...,2.60,2.40,3.25,2.60,2.50,3.25,2.50,2.50,3.20,2.50
26,27,1,1,2008/2009,11,2008-11-09 00:00:00,492581,9993,9985,1,...,1.95,3.75,3.25,1.85,3.60,3.25,1.95,3.50,3.30,1.91
27,28,1,1,2008/2009,12,2008-11-16 00:00:00,492582,8342,8635,1,...,3.30,2.25,3.10,2.80,2.10,3.20,3.20,2.20,3.20,2.90
28,29,1,1,2008/2009,12,2008-11-15 00:00:00,492583,9987,9999,1,...,10.00,1.25,5.00,9.00,1.27,5.00,8.50,1.25,5.00,9.00
29,30,1,1,2008/2009,12,2008-11-15 00:00:00,492584,10000,9993,2,...,3.40,2.10,3.30,3.10,2.00,3.20,3.50,2.00,3.25,3.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25949,25950,24558,24558,2015/2016,4,2015-08-08 00:00:00,1992066,9956,7896,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25950,25951,24558,24558,2015/2016,4,2015-08-08 00:00:00,1992067,10199,9931,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25951,25952,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992068,10190,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25952,25953,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992069,9824,10179,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25953,25954,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992070,10192,10191,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25954,25955,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992071,9931,10191,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25955,25956,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992072,10192,7896,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25956,25957,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992073,10199,10190,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25957,25958,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992074,10179,10243,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25958,25959,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992075,9824,9956,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25959,25960,24558,24558,2015/2016,6,2015-08-22 00:00:00,1992076,7896,9931,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25960,25961,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992077,10179,10192,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25961,25962,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992078,10190,9956,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25962,25963,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992079,10191,9824,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25963,25964,24558,24558,2015/2016,6,2015-08-22 00:00:00,1992080,10243,10199,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25964,25965,24558,24558,2015/2016,7,2015-08-29 00:00:00,1992081,7896,10199,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25965,25966,24558,24558,2015/2016,7,2015-08-29 00:00:00,1992082,9824,10190,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25966,25967,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992083,10191,10179,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25967,25968,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992084,9931,10243,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25968,25969,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992085,9956,10192,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25969,25970,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992086,9931,10190,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25970,25971,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992087,10192,9824,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25971,25972,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992088,10199,9956,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25972,25973,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992089,10243,10191,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25973,25974,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992090,10179,7896,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
Player_Attributes

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
5,6,189615,155782,2016-04-21 00:00:00,74.0,76.0,left,high,medium,80.0,...,66.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
6,7,189615,155782,2016-04-07 00:00:00,74.0,76.0,left,high,medium,80.0,...,66.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
7,8,189615,155782,2016-01-07 00:00:00,73.0,75.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
8,9,189615,155782,2015-12-24 00:00:00,73.0,75.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
9,10,189615,155782,2015-12-17 00:00:00,73.0,75.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
10,11,189615,155782,2015-10-16 00:00:00,73.0,77.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
11,12,189615,155782,2015-09-25 00:00:00,74.0,78.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
12,13,189615,155782,2015-09-21 00:00:00,73.0,77.0,left,medium,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
13,14,189615,155782,2015-01-09 00:00:00,71.0,75.0,left,medium,medium,78.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
14,15,189615,155782,2014-12-05 00:00:00,71.0,77.0,left,medium,medium,78.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
15,16,189615,155782,2014-11-07 00:00:00,71.0,77.0,left,medium,medium,78.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
16,17,189615,155782,2014-09-18 00:00:00,70.0,77.0,left,medium,medium,77.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
17,18,189615,155782,2014-05-02 00:00:00,70.0,79.0,left,medium,medium,77.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
18,19,189615,155782,2014-04-04 00:00:00,70.0,79.0,left,medium,medium,77.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
19,20,189615,155782,2014-03-14 00:00:00,70.0,79.0,left,medium,medium,77.0,...,61.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
20,21,189615,155782,2013-12-13 00:00:00,70.0,79.0,left,medium,medium,77.0,...,61.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
21,22,189615,155782,2013-11-08 00:00:00,70.0,79.0,left,medium,medium,77.0,...,61.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
22,23,189615,155782,2013-10-04 00:00:00,69.0,79.0,left,medium,medium,77.0,...,58.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
23,24,189615,155782,2013-09-20 00:00:00,69.0,79.0,left,medium,medium,77.0,...,58.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
24,25,189615,155782,2013-05-03 00:00:00,69.0,80.0,left,medium,medium,77.0,...,58.0,58.0,72.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
25,26,189615,155782,2013-03-22 00:00:00,69.0,80.0,left,medium,medium,77.0,...,58.0,58.0,72.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
26,27,189615,155782,2013-03-15 00:00:00,69.0,80.0,left,medium,medium,77.0,...,58.0,58.0,72.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
27,28,189615,155782,2013-02-22 00:00:00,69.0,80.0,left,medium,medium,77.0,...,58.0,58.0,72.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
28,29,189615,155782,2013-02-15 00:00:00,69.0,80.0,left,medium,medium,77.0,...,58.0,58.0,72.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
29,30,189615,155782,2012-08-31 00:00:00,68.0,80.0,left,medium,medium,77.0,...,63.0,58.0,72.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183948,183949,164680,111182,2012-02-22 00:00:00,68.0,76.0,left,medium,medium,73.0,...,45.0,53.0,64.0,68.0,66.0,9.0,8.0,5.0,5.0,8.0
183949,183950,164680,111182,2011-08-30 00:00:00,68.0,76.0,left,medium,medium,73.0,...,45.0,53.0,64.0,68.0,66.0,9.0,8.0,5.0,5.0,8.0
183950,183951,164680,111182,2011-02-22 00:00:00,68.0,79.0,left,medium,medium,71.0,...,65.0,53.0,71.0,69.0,69.0,9.0,8.0,5.0,5.0,8.0
183951,183952,164680,111182,2010-08-30 00:00:00,67.0,77.0,left,medium,medium,68.0,...,65.0,44.0,75.0,70.0,67.0,9.0,8.0,5.0,5.0,8.0
183952,183953,164680,111182,2007-02-22 00:00:00,67.0,77.0,left,medium,medium,68.0,...,65.0,44.0,75.0,70.0,67.0,9.0,8.0,5.0,5.0,8.0
183953,183954,111191,36491,2011-02-22 00:00:00,68.0,73.0,left,None,_0,64.0,...,66.0,61.0,67.0,71.0,59.0,15.0,13.0,5.0,6.0,6.0
183954,183955,111191,36491,2010-08-30 00:00:00,68.0,73.0,left,None,_0,64.0,...,66.0,61.0,71.0,71.0,59.0,15.0,13.0,5.0,6.0,6.0
183955,183956,111191,36491,2009-08-30 00:00:00,68.0,74.0,left,None,_0,64.0,...,66.0,61.0,71.0,71.0,59.0,4.0,21.0,61.0,21.0,21.0
183956,183957,111191,36491,2009-02-22 00:00:00,68.0,74.0,left,None,_0,64.0,...,66.0,61.0,71.0,71.0,59.0,4.0,21.0,61.0,21.0,21.0
183957,183958,111191,36491,2008-08-30 00:00:00,67.0,72.0,left,None,_0,62.0,...,66.0,61.0,61.0,62.0,59.0,4.0,21.0,61.0,21.0,21.0
183958,183959,111191,36491,2007-08-30 00:00:00,67.0,72.0,left,None,_0,62.0,...,66.0,61.0,43.0,52.0,59.0,4.0,21.0,52.0,21.0,21.0
183959,183960,111191,36491,2007-02-22 00:00:00,67.0,72.0,left,None,_0,62.0,...,66.0,61.0,43.0,52.0,59.0,4.0,21.0,52.0,21.0,21.0
183960,183961,47058,35506,2011-02-22 00:00:00,67.0,78.0,right,None,_0,48.0,...,63.0,45.0,65.0,66.0,65.0,14.0,7.0,15.0,10.0,12.0
183961,183962,47058,35506,2010-08-30 00:00:00,67.0,78.0,right,None,_0,48.0,...,63.0,45.0,65.0,66.0,65.0,14.0,7.0,15.0,10.0,12.0
183962,183963,47058,35506,2010-02-22 00:00:00,67.0,78.0,right,None,_0,48.0,...,63.0,70.0,65.0,66.0,65.0,14.0,25.0,51.0,25.0,25.0
183963,183964,47058,35506,2009-08-30 00:00:00,70.0,78.0,right,None,_0,48.0,...,63.0,70.0,70.0,74.0,65.0,14.0,25.0,51.0,25.0,25.0
183964,183965,47058,35506,2009-02-22 00:00:00,70.0,78.0,right,None,_0,48.0,...,63.0,70.0,70.0,74.0,65.0,14.0,25.0,51.0,25.0,25.0
183965,183966,47058,35506,2008-08-30 00:00:00,72.0,78.0,right,None,_0,48.0,...,63.0,70.0,76.0,78.0,65.0,14.0,25.0,51.0,25.0,25.0
183966,183967,47058,35506,2007-08-30 00:00:00,75.0,78.0,right,None,_0,48.0,...,63.0,70.0,76.0,78.0,65.0,14.0,25.0,51.0,25.0,25.0
183967,183968,47058,35506,2007-02-22 00:00:00,78.0,79.0,right,None,_0,38.0,...,63.0,72.0,79.0,84.0,65.0,14.0,9.0,48.0,7.0,11.0
183968,183969,102359,39902,2012-08-31 00:00:00,78.0,78.0,right,medium,low,77.0,...,82.0,78.0,22.0,31.0,30.0,9.0,13.0,8.0,15.0,5.0
183969,183970,102359,39902,2012-02-22 00:00:00,81.0,81.0,right,medium,low,80.0,...,87.0,78.0,22.0,31.0,30.0,9.0,13.0,8.0,15.0,5.0
183970,183971,102359,39902,2011-08-30 00:00:00,81.0,81.0,right,medium,low,80.0,...,87.0,78.0,22.0,31.0,30.0,9.0,13.0,8.0,15.0,5.0
183971,183972,102359,39902,2011-02-22 00:00:00,81.0,85.0,right,medium,low,81.0,...,87.0,73.0,22.0,31.0,30.0,9.0,13.0,8.0,15.0,5.0
183972,183973,102359,39902,2010-08-30 00:00:00,83.0,85.0,right,medium,low,84.0,...,88.0,73.0,22.0,31.0,30.0,9.0,13.0,8.0,15.0,5.0
183973,183974,102359,39902,2009-08-30 00:00:00,83.0,85.0,right,medium,low,84.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183975,102359,39902,2009-02-22 00:00:00,78.0,80.0,right,medium,low,74.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183976,102359,39902,2008-08-30 00:00:00,77.0,80.0,right,medium,low,74.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183977,102359,39902,2007-08-30 00:00:00,78.0,81.0,right,medium,low,74.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183978,102359,39902,2007-02-22 00:00:00,80.0,81.0,right,medium,low,74.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

In [33]:
Match.loc[Match['home_player_X1'] == 'NaN']

E:\Anaconda\lib\site-packages\pandas\core\ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

Empty DataFrame
Columns: [id, country_id, league_id, season, stage, date, match_api_id, home_team_api_id, away_team_api_id, home_team_goal, away_team_goal, home_player_X1, home_player_X2, home_player_X3, home_player_X4, home_player_X5, home_player_X6, home_player_X7, home_player_X8, home_player_X9, home_player_X10, home_player_X11, away_player_X1, away_player_X2, away_player_X3, away_player_X4, away_player_X5, away_player_X6, away_player_X7, away_player_X8, away_player_X9, away_player_X10, away_player_X11, home_player_Y1, home_player_Y2, home_player_Y3, home_player_Y4, home_player_Y5, home_player_Y6, home_player_Y7, home_player_Y8, home_player_Y9, home_player_Y10, home_player_Y11, away_player_Y1, away_player_Y2, away_player_Y3, away_player_Y4, away_player_Y5, away_player_Y6, away_player_Y7, away_player_Y8, away_player_Y9, away_player_Y10, away_player_Y11, home_player_1, home_player_2, home_player_3, home_player_4, home_player_5, home_player_6, home_player_7, home_player_8, home_player_9, home_player_10, home_player_11, away_player_1, away_player_2, away_player_3, away_player_4, away_player_5, away_player_6, away_player_7, away_player_8, away_player_9, away_player_10, away_player_11, goal, shoton, shotoff, foulcommit, card, cross, corner, possession, B365H, B365D, B365A, BWH, BWD, BWA, IWH, IWD, IWA, LBH, LBD, LBA, PSH, PSD, PSA, ...]
Index: []

[0 rows x 115 columns]